import image1 from "./asset/Rectangle 2039.jpg";

const cardData = [
  {
    id: "1",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "2",
    images: [image1, image1, image1],
    rating: 4.2,
    heading: "Sea Laas Vie",
    reviews: "100 reviews",
    ratingvalue: "4.2",
  },
  {
    id: "3",
    images: [image1, image1, image1],
    rating: 3.5,
    heading: "Fred- The weekend Home",
    reviews: "109 reviews",
    ratingvalue: "3.5",
  },
  {
    id: "4",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "5",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "6",
    images: [image1, image1, image1],
    rating: 3.5,
    heading: "Sea La Vie",
    reviews: "90 reviews",
    ratingvalue: "3.5",
  },
  {
    id: "7",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "8",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "9",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "10",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "11",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
  {
    id: "12",
    images: [image1, image1, image1],
    rating: 4.5,
    heading: "Sea La Vie",
    reviews: "105 reviews",
    ratingvalue: "4.5",
  },
];

export default cardData;
